import { Item, Shop } from "@/types";

export const FEATURED_SHOPS: Shop[] = [
  {
    id: "1",
    name: "PrintCraft Studio",
    slug: "printcraft-studio",
    description: "Premium 3D printed figurines and collectibles",
    logo: "https://api.dicebear.com/9.x/initials/svg?seed=PC",
    coverImage: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800",
    owner: { id: "u1", name: "Rahul Sharma", email: "rahul@mail.com", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul" },
    rating: 4.8,
    totalSales: 342,
    items: [],
    createdAt: "2025-06-15",
  },
  {
    id: "2",
    name: "3D Wonders",
    slug: "3d-wonders",
    description: "Custom home decor and functional prints",
    logo: "https://api.dicebear.com/9.x/initials/svg?seed=3W",
    coverImage: "https://images.unsplash.com/photo-1563520239648-a24e051a5e76?w=800",
    owner: { id: "u2", name: "Priya Patel", email: "priya@mail.com", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya" },
    rating: 4.6,
    totalSales: 218,
    items: [],
    createdAt: "2025-08-20",
  },
  {
    id: "3",
    name: "MakerSpace India",
    slug: "makerspace-india",
    description: "Innovative gadgets and tools, made with precision",
    logo: "https://api.dicebear.com/9.x/initials/svg?seed=MI",
    coverImage: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800",
    owner: { id: "u3", name: "Amit Kumar", email: "amit@mail.com", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Amit" },
    rating: 4.9,
    totalSales: 567,
    items: [],
    createdAt: "2025-03-10",
  },
];

export const TRENDING_ITEMS: Item[] = [
  {
    id: "i1",
    title: "Dragon Figurine - Detailed",
    description: "Highly detailed dragon figurine with intricate scales and wings. Perfect for collectors and fantasy enthusiasts.",
    price: 1499,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600"],
    category: "figurines",
    material: "PLA+",
    dimensions: "15cm x 10cm x 12cm",
    inStock: true,
    shop: FEATURED_SHOPS[0],
    rating: 4.9,
    reviews: 48,
    createdAt: "2025-12-01",
  },
  {
    id: "i2",
    title: "Geometric Planter Set",
    description: "Modern geometric planters set of 3. Minimalist design perfect for succulents and small plants.",
    price: 899,
    images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
    category: "home-decor",
    material: "PETG",
    dimensions: "8cm x 8cm x 10cm each",
    inStock: true,
    shop: FEATURED_SHOPS[1],
    rating: 4.7,
    reviews: 35,
    createdAt: "2025-11-15",
  },
  {
    id: "i3",
    title: "Cable Management Clips (10 Pack)",
    description: "Keep your desk tidy with these smart cable management clips. Adhesive backing for easy installation.",
    price: 299,
    images: ["https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?w=600"],
    category: "functional",
    material: "ABS",
    dimensions: "3cm x 2cm x 1.5cm",
    inStock: true,
    shop: FEATURED_SHOPS[2],
    rating: 4.5,
    reviews: 120,
    createdAt: "2025-10-20",
  },
  {
    id: "i4",
    title: "Articulated Octopus Toy",
    description: "Fun fidget toy with fully articulated tentacles. Great stress reliever and conversation starter.",
    price: 499,
    images: ["https://images.unsplash.com/photo-1590677880117-eda20dfbe009?w=600"],
    category: "toys",
    material: "TPU",
    dimensions: "12cm x 12cm x 5cm",
    inStock: true,
    shop: FEATURED_SHOPS[0],
    rating: 4.8,
    reviews: 89,
    createdAt: "2025-12-10",
  },
  {
    id: "i5",
    title: "Mandala Wall Art",
    description: "Beautiful mandala pattern wall art. Lightweight and easy to hang. Available in multiple colors.",
    price: 1299,
    images: ["https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600"],
    category: "art",
    material: "PLA",
    dimensions: "30cm x 30cm x 1cm",
    inStock: true,
    shop: FEATURED_SHOPS[1],
    rating: 4.6,
    reviews: 22,
    createdAt: "2025-11-28",
  },
  {
    id: "i6",
    title: "Custom Phone Stand",
    description: "Adjustable phone stand with cable routing. Works with all phone sizes. Sturdy and portable.",
    price: 399,
    images: ["https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600"],
    category: "gadgets",
    material: "PETG",
    dimensions: "10cm x 8cm x 12cm",
    inStock: true,
    shop: FEATURED_SHOPS[2],
    rating: 4.7,
    reviews: 64,
    createdAt: "2025-12-05",
  },
];
